### ISSUE TITLE
Support `type` as field name on schema

### ISSUE THREAD

**Issue by sakti** [openquery-io/synth#1]
**Required Functionality**
Currently for schema generator, synth use `key`: `value`. `key` for field / column name and `value` contain schema description. Therefore using string literal `type` will conflict with schema definition container object.

**Proposed Solution**

**Use case**
Example conflicted schema:

```
{
  "type": "array",
  "length": {
    "type": "number",
    "range": {
      "high": 1,
      "low": 0,
      "step": 1
    },
    "subtype": "u64"
  },
  "content": {
    "type": "object",
    "ip_address": {
      "optional": true,
      "type": "string",
      "pattern": "[a-zA-Z0-9]{0, 45}"
    },
    "user_agent": {
      "optional": true,
      "type": "string",
      "pattern": "[a-zA-Z0-9]{0, 1000}"
    },
    "hash": {
      "optional": true,
      "type": "string",
      "pattern": "[a-zA-Z0-9]{0, 64}"
    },
    "user_id": {
      "optional": true,
      "type": "string",
      "pattern": "[a-zA-Z0-9]{0, 50}"
    },
    "type": { <-- Duplicate Object key
      "optional": true,
      "type": "string",
      "pattern": "[a-zA-Z0-9]{0, 5}"
    },
    "created_at": {
      "type": "string",
      "date_time": {
        "format": "%Y-%m-%d %H:%M:%S%Z",
        "subtype": "date_time",
        "begin": null,
        "end": null
      }
    },
    "id": {
      "type": "number",
      "id": {},
      "subtype": "u64"
    }
  }
}
```

**Comment by christoshadjiaslanis** [comment]
Thanks for this! I'm surprised it hasn't popped up already. Will fix and add to an upcoming release.

**Comment by llogiq** [comment]
I'm going to write this down here to both collect my thoughts and show my openness for discussion regarding the proposed solution:

1. As a workaround, we'll allow the `"type_"` key, which will automatically be associated with the attribute named `type` without clashing with our internal `"type"` key. Note that we will only allow this for this one key.  
2. I think the problem stems from mixing predefined keys and attribute names. Introducing a clear split between those would be the better solution from a design stand point. If we introduce such a change, we'll allow both variants for a while and then introduce warnings for the old variant that show the required change. After a while, we remove the old variant.

**Comment by llogiq** [comment]
The workaround is in (version 0.4.4), and I'm going to postpone the rest. We can close this for now.
