### ISSUE TITLE
--random and --seed not working when using postgres generator

### ISSUE THREAD

**Issue by andrena-eike-kohnert** [openquery-io/synth#7]
When using postgres as target, the parameters --random and --seed are ignored. 

**Expected behavior**

When running generation with postgres target and --random flag twice, function like uuid should generate different data. Instead the same data is generated for each run.

**Additional context**

I looked at the source code. In synth/src/cli/postgres.rs the function Sampler::sample is used which always uses seed 0. I guess this should be changed to Sampler::sample_seeded ?

**Comment by llogiq** [comment]
Good catch, thank you! This should be an easy fix.

**Comment by christoshadjiaslanis** [comment]
Fixed in release v0.4.6-r2.

**Comment by andrena-eike-kohnert** [comment]
Thanks a lot for your quick help!
